# Generated by Django 3.1.3 on 2023-06-05 04:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinfo',
            name='awakeNum',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='sleepNum',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='stateNo',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lectureinfo',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resultinfo',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tutorinfo',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
