# Generated by Django 4.2.2 on 2023-06-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollinfo',
            name='enroll',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
