# Generated by Django 3.1.3 on 2023-06-05 05:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ocds', '0002_auto_20230605_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='continued_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lectureinfo',
            name='lecture_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lectureinfo',
            name='lecture_name',
            field=models.CharField(default='강사명', max_length=100),
        ),
        migrations.AlterField(
            model_name='lectureinfo',
            name='lecture_url',
            field=models.CharField(default='https://example.com/default-url', max_length=250),
        ),
        migrations.AlterField(
            model_name='lectureinfo',
            name='recommended',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='resultinfo',
            name='capture_end',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resultinfo',
            name='capture_start',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resultinfo',
            name='end_log',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='resultinfo',
            name='start_log',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tutorinfo',
            name='email',
            field=models.CharField(default='default@example.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='tutorinfo',
            name='password',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='tutorinfo',
            name='tutor_name',
            field=models.CharField(default='홍길동', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default='default@example.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(default='홍길동', max_length=50),
        ),
    ]
