# Generated by Django 3.1.3 on 2023-06-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocds', '0003_auto_20230605_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='stateNo',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
