# Generated by Django 4.1.5 on 2023-06-08 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ocds", "0005_auto_20230605_1649"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventinfo",
            old_name="awakeNum",
            new_name="awake",
        ),
        migrations.RenameField(
            model_name="eventinfo",
            old_name="sleepNum",
            new_name="sleep",
        ),
        migrations.RemoveField(
            model_name="eventinfo",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="eventinfo",
            name="start_time",
        ),
        migrations.RemoveField(
            model_name="eventinfo",
            name="stateNo",
        ),
    ]
