# Generated by Django 4.1.5 on 2023-06-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocds", "0006_rename_awakenum_eventinfo_awake_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventinfo",
            name="stateNo",
            field=models.IntegerField(default=0),
        ),
    ]
